### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by F1shbone** [F1shbone/config#1]
- [x] https://github.com/mubaidr/vuejs-extension-pack/blob/master/package.json
- [x] VSCE pack extensions 
- [x] Add 'Open Folder in VS Code' Service to readme
- [x] https://github.com/mdo/config
